"""
secp256k1 key derivation from fuzzy-extractor key material. Ported from
siliconwitness's gateway/puf/keys.py. The derived address IS the camera's
account identity (`cmosAccount`) -- it can only be regenerated by re-reading
the same physical sensor's defect pattern.
"""

from __future__ import annotations

import hashlib

from eth_keys import keys as eth_keys_lib
from eth_keys.exceptions import ValidationError

from .puf_fuzzy_extractor import zero_bytearray


def derive_private_key(key_material: bytearray) -> "eth_keys_lib.PrivateKey":
    """key_material: 32-byte SHA256 digest from the fuzzy extractor. Rare
    edge case: a raw digest can land on 0 or on/above the secp256k1 curve
    order, an invalid private key -- handled by re-hashing with a counter
    appended (still fully deterministic from the same input)."""
    material = bytes(key_material)
    for counter in range(256):
        candidate = (
            material
            if counter == 0
            else hashlib.sha256(material + bytes([counter])).digest()
        )
        try:
            return eth_keys_lib.PrivateKey(candidate)
        except (ValidationError, Exception):
            continue
    raise RuntimeError(
        "Could not derive a valid secp256k1 private key after 256 attempts."
    )


def derive_address(private_key: "eth_keys_lib.PrivateKey") -> str:
    return private_key.public_key.to_checksum_address()


def zero_key_material(
    key_material: bytearray, private_key: "eth_keys_lib.PrivateKey"
) -> None:
    zero_bytearray(key_material)
    try:
        pk_bytes = bytearray(private_key.to_bytes())
        zero_bytearray(pk_bytes)
    except Exception:
        pass


def sign_and_zero(key_material: bytearray, message_hash: bytes) -> str:
    """Derive the private key, sign message_hash (32 bytes), zero key material,
    return '0x...'-prefixed hex signature. Ported from siliconwitness
    gateway/puf/keys.py::sign_and_zero."""
    if len(message_hash) != 32:
        raise ValueError("message_hash must be exactly 32 bytes (pre-hashed)")

    pk = derive_private_key(key_material)
    sig = pk.sign_msg_hash(message_hash)
    sig_hex = "0x" + bytes(sig).hex()
    zero_key_material(key_material, pk)
    del pk
    return sig_hex
